"""The Builder->Reviewer handoff bridge: a durable, file-based review-packet inbox.

Builder finishes a task and *emits* a schema-validated review packet; Reviewer *detects* and audits it.
Neither side needs the other to be online, and no agent-chat channel is involved — see
`docs/PROTOCOL.md` for the runbook and `docs/PROTOCOL.md` for the law.

A Claude Code `Stop` hook (`src/twoperson/scripts/twoperson_stop_hook.sh`, registered by `install_hook`) emits a
lightweight completion *signal* so the detection step needs no timer. A signal is not a packet and
does not satisfy the audit gate — see `src/twoperson/signal.py`.

Submodules are imported lazily by the CLI; import this package for the public names.
"""
from __future__ import annotations

from .hook import HookInstallError, hook_settings, install_hook
from .inbox import (
    Claimed,
    ack_advice,
    ack_signals,
    ack_verdicts,
    answered_consult_ids,
    archive_claimed,
    archive_claimed_consult,
    archived,
    archived_consults,
    claim_consult,
    claim_next,
    claimed,
    claimed_consults,
    has_pending,
    has_pending_advice,
    has_pending_consults,
    has_pending_signals,
    has_pending_verdicts,
    inbox_root,
    peek_consult,
    peek_next,
    pending,
    pending_advice,
    pending_consults,
    pending_signals,
    pending_verdicts,
    publish,
    publish_advice,
    publish_consult,
    publish_signal,
    publish_verdict,
    read_advice,
    read_signals,
    read_verdicts,
    requeue_claimed,
    requeue_claimed_consult,
    verdicted_packet_ids,
)
from .consult import (
    AREAS,
    CONSULT_KIND,
    CONSULT_SCHEMA_VERSION,
    build_consult,
    render_for_consult,
    template_consult,
    validate_consult,
)
from .advice import (
    ADVICE_KIND,
    ADVICE_SCHEMA_VERSION,
    CONFIDENCES,
    build_advice,
    render_advice,
    validate_advice,
)
from .signal import (
    SIGNAL_KIND,
    SIGNAL_SCHEMA_VERSION,
    build_signal,
    render_signal,
    validate_signal,
)
from .verdict import (
    DECISIONS,
    SHIP_DECISIONS,
    VERDICT_KIND,
    VERDICT_SCHEMA_VERSION,
    build_verdict,
    render_verdict,
    unlocks_ship,
    validate_verdict,
)
from .packet import (
    SCHEMA_VERSION,
    PacketError,
    SchemaError,
    SecretLeakError,
    UnsafePathError,
    render_for_review,
    template_packet,
    validate_packet,
)
from .watch import (
    Cursor,
    DispatchReport,
    WatchDelta,
    dispatch_once,
    is_muted,
    scan_new,
    set_muted,
    watch_loop,
)
from .watchagent import (
    AGENT_LABEL,
    WatchInstallError,
    install_watch_agent,
    render_plist,
)

__all__ = [
    "AGENT_LABEL",
    "ADVICE_KIND",
    "ADVICE_SCHEMA_VERSION",
    "AREAS",
    "CONFIDENCES",
    "CONSULT_KIND",
    "CONSULT_SCHEMA_VERSION",
    "DECISIONS",
    "SCHEMA_VERSION",
    "SIGNAL_KIND",
    "SIGNAL_SCHEMA_VERSION",
    "SHIP_DECISIONS",
    "VERDICT_KIND",
    "VERDICT_SCHEMA_VERSION",
    "Claimed",
    "Cursor",
    "DispatchReport",
    "HookInstallError",
    "PacketError",
    "SchemaError",
    "SecretLeakError",
    "UnsafePathError",
    "WatchDelta",
    "WatchInstallError",
    "ack_advice",
    "ack_signals",
    "answered_consult_ids",
    "archive_claimed",
    "archive_claimed_consult",
    "archived",
    "archived_consults",
    "build_advice",
    "build_consult",
    "claim_consult",
    "claimed",
    "claimed_consults",
    "has_pending_advice",
    "has_pending_consults",
    "peek_consult",
    "pending_advice",
    "pending_consults",
    "publish_advice",
    "publish_consult",
    "read_advice",
    "render_advice",
    "render_for_consult",
    "template_consult",
    "validate_advice",
    "validate_consult",
    "dispatch_once",
    "is_muted",
    "set_muted",
    "install_watch_agent",
    "render_plist",
    "scan_new",
    "watch_loop",
    "ack_verdicts",
    "build_signal",
    "build_verdict",
    "claim_next",
    "has_pending",
    "has_pending_signals",
    "has_pending_verdicts",
    "hook_settings",
    "inbox_root",
    "install_hook",
    "peek_next",
    "pending",
    "pending_signals",
    "pending_verdicts",
    "publish",
    "publish_signal",
    "publish_verdict",
    "read_signals",
    "read_verdicts",
    "render_for_review",
    "render_signal",
    "render_verdict",
    "requeue_claimed",
    "requeue_claimed_consult",
    "template_packet",
    "unlocks_ship",
    "validate_packet",
    "validate_signal",
    "validate_verdict",
    "verdicted_packet_ids",
]
